import request from "@/utils/axiosUtils";
import useFetchQuery from "@/utils/hooks/useFetchQuery";
import { useEffect, useState } from "react";
import MenuList from "./MenuList";

const MainHeaderMenu = () => {
  const [isOpen, setIsOpen] = useState([]);
  const {
    data: headerMenu,
    refetch,
    isLoading,
    fetchStatus,
  } = useFetchQuery(["menu"], () => request({ url: "/menu" }), {
    select: (res) => {
      const originalData = res.data.data;
      const modifiedData = originalData.map((item) => ({
        ...item,
        class: `${["Product", "Mega Menu"].includes(item.title) ? 1 : 0}`,
      }));

      return modifiedData;
    },
    refetchOnWindowFocus: true,
    enabled: false,
  });
  const demoMenu = [
    {
      id: 2,
      title: "Home",
      sort: "0",
      link_type: "link",
      is_target_blank: 0,
      mega_menu: 0,
      mega_menu_type: "simple",
      slug: "home",
      type: null,
      path: "/",
      badge_text: null,
      badge_color: null,
      content_item: null,
      item_image_id: null,
      banner_image_id: null,
      set_page_link: null,
      parent_id: null,
      created_by_id: "1",
      created_at: "2024-05-03T05:12:01.000000Z",
      product_ids: [],
      blog_ids: [],
      item_image: null,
      banner_image: null,
      child: [],
    },
    //  {
    //     "id": 57,
    //     "title": "Apple Products",
    //     "sort": "5",
    //     "link_type": "sub",
    //     "is_target_blank": 0,
    //     "mega_menu": 0,
    //     "mega_menu_type": "simple",
    //     "slug": "apple products",
    //     "type": null,
    //     "path": null,
    //     "badge_text": null,
    //     "badge_color": null,
    //     "content_item": null,
    //     "item_image_id": null,
    //     "banner_image_id": null,
    //     "set_page_link": null,
    //     "parent_id": null,
    //     "created_by_id": "1",
    //     "created_at": "2024-06-19T13:36:23.000000Z",
    //     "product_ids": [],
    //     "blog_ids": [],
    //     "item_image": null,
    //     "banner_image": null,
    //     "child": [
    //         {
    //             "id": 58,
    //             "title": "iPhone",
    //             "sort": "0",
    //             "link_type": "sub",
    //             "is_target_blank": 0,
    //             "mega_menu": 0,
    //             "mega_menu_type": "simple",
    //             "slug": "account",
    //             "type": null,
    //             "path": null,
    //             "badge_text": null,
    //             "badge_color": null,
    //             "content_item": null,
    //             "item_image_id": null,
    //             "banner_image_id": null,
    //             "set_page_link": null,
    //             "parent_id": 57,
    //             "created_by_id": "1",
    //             "created_at": "2024-06-19T13:45:11.000000Z",
    //             "product_ids": [],
    //             "blog_ids": [],
    //             "item_image": null,
    //             "banner_image": null,
    //             "child": [
    //                 {
    //                     "id": 59,
    //                     "title": "IPhone 17 Pro Max",
    //                     "sort": "0",
    //                     "link_type": "link",
    //                     "is_target_blank": 0,
    //                     "mega_menu": 0,
    //                     "mega_menu_type": null,
    //                     "slug": "my-dashboard",
    //                     "type": null,
    //                     "path": "/collections?layout=collection_left_sidebar",
    //                     "badge_text": null,
    //                     "badge_color": null,
    //                     "content_item": null,
    //                     "item_image_id": null,
    //                     "banner_image_id": null,
    //                     "set_page_link": null,
    //                     "parent_id": 58,
    //                     "created_by_id": "1",
    //                     "created_at": "2024-06-19T13:46:05.000000Z",
    //                     "product_ids": [],
    //                     "blog_ids": [],
    //                     "item_image": null,
    //                     "banner_image": null,
    //                     "child": []
    //                 },
    //                 {
    //                     "id": 60,
    //                     "title": "My Notifications",
    //                     "sort": "1",
    //                     "link_type": "link",
    //                     "is_target_blank": 0,
    //                     "mega_menu": 0,
    //                     "mega_menu_type": null,
    //                     "slug": "my-notifications",
    //                     "type": null,
    //                     "path": "/collections?layout=collection_left_sidebar",
    //                     "badge_text": null,
    //                     "badge_color": null,
    //                     "content_item": null,
    //                     "item_image_id": null,
    //                     "banner_image_id": null,
    //                     "set_page_link": null,
    //                     "parent_id": 58,
    //                     "created_by_id": "1",
    //                     "created_at": "2024-06-19T13:46:58.000000Z",
    //                     "product_ids": [],
    //                     "blog_ids": [],
    //                     "item_image": null,
    //                     "banner_image": null,
    //                     "child": []
    //                 },
    //                 {
    //                     "id": 61,
    //                     "title": "Bank Details",
    //                     "sort": "2",
    //                     "link_type": "link",
    //                     "is_target_blank": 0,
    //                     "mega_menu": 0,
    //                     "mega_menu_type": null,
    //                     "slug": "bank-details",
    //                     "type": null,
    //                     "path": "/collections?layout=collection_left_sidebar",
    //                     "badge_text": null,
    //                     "badge_color": null,
    //                     "content_item": null,
    //                     "item_image_id": null,
    //                     "banner_image_id": null,
    //                     "set_page_link": null,
    //                     "parent_id": 58,
    //                     "created_by_id": "1",
    //                     "created_at": "2024-06-19T13:48:17.000000Z",
    //                     "product_ids": [],
    //                     "blog_ids": [],
    //                     "item_image": null,
    //                     "banner_image": null,
    //                     "child": []
    //                 },
    //                 {
    //                     "id": 62,
    //                     "title": "My Wallet",
    //                     "sort": "3",
    //                     "link_type": "link",
    //                     "is_target_blank": 0,
    //                     "mega_menu": 0,
    //                     "mega_menu_type": null,
    //                     "slug": "my-wallet",
    //                     "type": null,
    //                     "path": "/collections?layout=collection_left_sidebar",
    //                     "badge_text": null,
    //                     "badge_color": null,
    //                     "content_item": null,
    //                     "item_image_id": null,
    //                     "banner_image_id": null,
    //                     "set_page_link": null,
    //                     "parent_id": 58,
    //                     "created_by_id": "1",
    //                     "created_at": "2024-06-19T13:50:18.000000Z",
    //                     "product_ids": [],
    //                     "blog_ids": [],
    //                     "item_image": null,
    //                     "banner_image": null,
    //                     "child": []
    //                 },
    //                 {
    //                     "id": 63,
    //                     "title": "My point",
    //                     "sort": "4",
    //                     "link_type": "link",
    //                     "is_target_blank": 0,
    //                     "mega_menu": 0,
    //                     "mega_menu_type": null,
    //                     "slug": "my-point",
    //                     "type": null,
    //                     "path": "/collections?layout=collection_left_sidebar",
    //                     "badge_text": null,
    //                     "badge_color": null,
    //                     "content_item": null,
    //                     "item_image_id": null,
    //                     "banner_image_id": null,
    //                     "set_page_link": null,
    //                     "parent_id": 58,
    //                     "created_by_id": "1",
    //                     "created_at": "2024-06-19T13:50:53.000000Z",
    //                     "product_ids": [],
    //                     "blog_ids": [],
    //                     "item_image": null,
    //                     "banner_image": null,
    //                     "child": []
    //                 },
    //                 {
    //                     "id": 64,
    //                     "title": "My Order",
    //                     "sort": "5",
    //                     "link_type": "link",
    //                     "is_target_blank": 0,
    //                     "mega_menu": 0,
    //                     "mega_menu_type": null,
    //                     "slug": "my-order",
    //                     "type": null,
    //                     "path": "/collections?layout=collection_left_sidebar",
    //                     "badge_text": null,
    //                     "badge_color": null,
    //                     "content_item": null,
    //                     "item_image_id": null,
    //                     "banner_image_id": null,
    //                     "set_page_link": null,
    //                     "parent_id": 58,
    //                     "created_by_id": "1",
    //                     "created_at": "2024-06-19T13:51:57.000000Z",
    //                     "product_ids": [],
    //                     "blog_ids": [],
    //                     "item_image": null,
    //                     "banner_image": null,
    //                     "child": []
    //                 },
    //                 {
    //                     "id": 65,
    //                     "title": "Refund History",
    //                     "sort": "6",
    //                     "link_type": "link",
    //                     "is_target_blank": 0,
    //                     "mega_menu": 0,
    //                     "mega_menu_type": null,
    //                     "slug": "refund-history",
    //                     "type": null,
    //                     "path": "/collections?layout=collection_left_sidebar",
    //                     "badge_text": null,
    //                     "badge_color": null,
    //                     "content_item": null,
    //                     "item_image_id": null,
    //                     "banner_image_id": null,
    //                     "set_page_link": null,
    //                     "parent_id": 58,
    //                     "created_by_id": "1",
    //                     "created_at": "2024-06-19T13:54:23.000000Z",
    //                     "product_ids": [],
    //                     "blog_ids": [],
    //                     "item_image": null,
    //                     "banner_image": null,
    //                     "child": []
    //                 }
    //             ]
    //         },
    //         {
    //             "id": 66,
    //             "title": "Macbook",
    //             "sort": "1",
    //             "link_type": "link",
    //             "is_target_blank": 0,
    //             "mega_menu": 0,
    //             "mega_menu_type": null,
    //             "slug": "about-us",
    //             "type": null,
    //             "path": "/about-us",
    //             "badge_text": null,
    //             "badge_color": null,
    //             "content_item": null,
    //             "item_image_id": null,
    //             "banner_image_id": null,
    //             "set_page_link": null,
    //             "parent_id": 57,
    //             "created_by_id": "1",
    //             "created_at": "2024-06-19T13:58:14.000000Z",
    //             "product_ids": [],
    //             "blog_ids": [],
    //             "item_image": null,
    //             "banner_image": null,
    //             "child": []
    //         },
    //         {
    //             "id": 67,
    //             "title": "Browse FAQs",
    //             "sort": "2",
    //             "link_type": "link",
    //             "is_target_blank": 0,
    //             "mega_menu": 0,
    //             "mega_menu_type": null,
    //             "slug": "browse-faqs",
    //             "type": null,
    //             "path": "/faq",
    //             "badge_text": null,
    //             "badge_color": null,
    //             "content_item": null,
    //             "item_image_id": null,
    //             "banner_image_id": null,
    //             "set_page_link": null,
    //             "parent_id": 57,
    //             "created_by_id": "1",
    //             "created_at": "2024-06-19T13:58:42.000000Z",
    //             "product_ids": [],
    //             "blog_ids": [],
    //             "item_image": null,
    //             "banner_image": null,
    //             "child": []
    //         },
    //         {
    //             "id": 68,
    //             "title": "Cart",
    //             "sort": "3",
    //             "link_type": "link",
    //             "is_target_blank": 0,
    //             "mega_menu": 0,
    //             "mega_menu_type": null,
    //             "slug": "cart",
    //             "type": null,
    //             "path": "/cart",
    //             "badge_text": null,
    //             "badge_color": null,
    //             "content_item": null,
    //             "item_image_id": null,
    //             "banner_image_id": null,
    //             "set_page_link": null,
    //             "parent_id": 57,
    //             "created_by_id": "1",
    //             "created_at": "2024-06-19T13:59:14.000000Z",
    //             "product_ids": [],
    //             "blog_ids": [],
    //             "item_image": null,
    //             "banner_image": null,
    //             "child": []
    //         },
    //         {
    //             "id": 72,
    //             "title": "Offers",
    //             "sort": "4",
    //             "link_type": "link",
    //             "is_target_blank": 0,
    //             "mega_menu": 0,
    //             "mega_menu_type": "simple",
    //             "slug": "offers",
    //             "type": null,
    //             "path": "/offers",
    //             "badge_text": null,
    //             "badge_color": null,
    //             "content_item": null,
    //             "item_image_id": null,
    //             "banner_image_id": null,
    //             "set_page_link": null,
    //             "parent_id": 57,
    //             "created_by_id": "1",
    //             "created_at": "2024-06-19T14:02:56.000000Z",
    //             "product_ids": [],
    //             "blog_ids": [],
    //             "item_image": null,
    //             "banner_image": null,
    //             "child": []
    //         },
    //         {
    //             "id": 71,
    //             "title": "Contact Us",
    //             "sort": "5",
    //             "link_type": "link",
    //             "is_target_blank": 0,
    //             "mega_menu": 0,
    //             "mega_menu_type": null,
    //             "slug": "contact-us",
    //             "type": null,
    //             "path": "/contact-us",
    //             "badge_text": null,
    //             "badge_color": null,
    //             "content_item": null,
    //             "item_image_id": null,
    //             "banner_image_id": null,
    //             "set_page_link": null,
    //             "parent_id": 57,
    //             "created_by_id": "1",
    //             "created_at": "2024-06-19T14:01:13.000000Z",
    //             "product_ids": [],
    //             "blog_ids": [],
    //             "item_image": null,
    //             "banner_image": null,
    //             "child": []
    //         },
    //         {
    //             "id": 70,
    //             "title": "Compare",
    //             "sort": "6",
    //             "link_type": "link",
    //             "is_target_blank": 0,
    //             "mega_menu": 0,
    //             "mega_menu_type": null,
    //             "slug": "compare",
    //             "type": null,
    //             "path": "/compare",
    //             "badge_text": null,
    //             "badge_color": null,
    //             "content_item": null,
    //             "item_image_id": null,
    //             "banner_image_id": null,
    //             "set_page_link": null,
    //             "parent_id": 57,
    //             "created_by_id": "1",
    //             "created_at": "2024-06-19T14:00:27.000000Z",
    //             "product_ids": [],
    //             "blog_ids": [],
    //             "item_image": null,
    //             "banner_image": null,
    //             "child": []
    //         },
    //         {
    //             "id": 69,
    //             "title": "Checkout",
    //             "sort": "7",
    //             "link_type": "link",
    //             "is_target_blank": 0,
    //             "mega_menu": 0,
    //             "mega_menu_type": null,
    //             "slug": "checkout",
    //             "type": null,
    //             "path": "/checkout",
    //             "badge_text": null,
    //             "badge_color": null,
    //             "content_item": null,
    //             "item_image_id": null,
    //             "banner_image_id": null,
    //             "set_page_link": null,
    //             "parent_id": 57,
    //             "created_by_id": "1",
    //             "created_at": "2024-06-19T13:59:57.000000Z",
    //             "product_ids": [],
    //             "blog_ids": [],
    //             "item_image": null,
    //             "banner_image": null,
    //             "child": []
    //         },
    //         {
    //             "id": 73,
    //             "title": "Search",
    //             "sort": "8",
    //             "link_type": "link",
    //             "is_target_blank": 0,
    //             "mega_menu": 0,
    //             "mega_menu_type": null,
    //             "slug": "search",
    //             "type": null,
    //             "path": "/search",
    //             "badge_text": "Hot",
    //             "badge_color": null,
    //             "content_item": null,
    //             "item_image_id": null,
    //             "banner_image_id": null,
    //             "set_page_link": null,
    //             "parent_id": 57,
    //             "created_by_id": "1",
    //             "created_at": "2024-06-19T14:03:38.000000Z",
    //             "product_ids": [],
    //             "blog_ids": [],
    //             "item_image": null,
    //             "banner_image": null,
    //             "child": []
    //         },
    //         {
    //             "id": 74,
    //             "title": "Wishlist",
    //             "sort": "9",
    //             "link_type": "link",
    //             "is_target_blank": 0,
    //             "mega_menu": 0,
    //             "mega_menu_type": null,
    //             "slug": "wishlist",
    //             "type": null,
    //             "path": "/wishlist",
    //             "badge_text": null,
    //             "badge_color": null,
    //             "content_item": null,
    //             "item_image_id": null,
    //             "banner_image_id": null,
    //             "set_page_link": null,
    //             "parent_id": 57,
    //             "created_by_id": "1",
    //             "created_at": "2024-06-19T14:06:37.000000Z",
    //             "product_ids": [],
    //             "blog_ids": [],
    //             "item_image": null,
    //             "banner_image": null,
    //             "child": []
    //         },
    //         {
    //             "id": 75,
    //             "title": "404",
    //             "sort": "10",
    //             "link_type": "link",
    //             "is_target_blank": 0,
    //             "mega_menu": 0,
    //             "mega_menu_type": null,
    //             "slug": "404",
    //             "type": null,
    //             "path": "/404",
    //             "badge_text": null,
    //             "badge_color": null,
    //             "content_item": null,
    //             "item_image_id": null,
    //             "banner_image_id": null,
    //             "set_page_link": null,
    //             "parent_id": 57,
    //             "created_by_id": "1",
    //             "created_at": "2024-06-19T14:08:06.000000Z",
    //             "product_ids": [],
    //             "blog_ids": [],
    //             "item_image": null,
    //             "banner_image": null,
    //             "child": []
    //         }
    //     ]
    // },
    {
      id: 57,
      title: "Apple Products",
      sort: "5",
      link_type: "sub",
      is_target_blank: 0,
      mega_menu: 0,
      mega_menu_type: "simple",
      slug: "apple products",
      type: null,
      path: null,
      badge_text: null,
      badge_color: null,
      content_item: null,
      item_image_id: null,
      banner_image_id: null,
      set_page_link: null,
      parent_id: null,
      created_by_id: "1",
      created_at: "2024-06-19T13:36:23.000000Z",
      product_ids: [],
      blog_ids: [],
      item_image: null,
      banner_image: null,
      child: [
        {
          id: 66,
          title: "Iphone",
          sort: "1",
          link_type: "link",
          is_target_blank: 0,
          mega_menu: 0,
          mega_menu_type: null,
          slug: "iphone",
          type: null,
          path: "/category/iphone",
          badge_text: null,
          badge_color: null,
          content_item: null,
          item_image_id: null,
          banner_image_id: null,
          set_page_link: null,
          parent_id: 57,
          created_by_id: "1",
          created_at: "2024-06-19T13:58:14.000000Z",
          product_ids: [],
          blog_ids: [],
          item_image: null,
          banner_image: null,
          child: [],
        },
        {
          id: 66,
          title: "Macbook",
          sort: "1",
          link_type: "link",
          is_target_blank: 0,
          mega_menu: 0,
          mega_menu_type: null,
          slug: "about-us",
          type: null,
          path: "/collections?layout=collection_left_sidebar",
          badge_text: null,
          badge_color: null,
          content_item: null,
          item_image_id: null,
          banner_image_id: null,
          set_page_link: null,
          parent_id: 57,
          created_by_id: "1",
          created_at: "2024-06-19T13:58:14.000000Z",
          product_ids: [],
          blog_ids: [],
          item_image: null,
          banner_image: null,
          child: [],
        },
        {
          id: 68,
          title: "Ipad",
          sort: "3",
          link_type: "link",
          is_target_blank: 0,
          mega_menu: 0,
          mega_menu_type: null,
          slug: "cart",
          type: null,
          path: "/collections?layout=collection_left_sidebar",
          badge_text: null,
          badge_color: null,
          content_item: null,
          item_image_id: null,
          banner_image_id: null,
          set_page_link: null,
          parent_id: 57,
          created_by_id: "1",
          created_at: "2024-06-19T13:59:14.000000Z",
          product_ids: [],
          blog_ids: [],
          item_image: null,
          banner_image: null,
          child: [],
        },
        {
          id: 72,
          title: "Airpod",
          sort: "4",
          link_type: "link",
          is_target_blank: 0,
          mega_menu: 0,
          mega_menu_type: "simple",
          slug: "offers",
          type: null,
          path: "/collections?layout=collection_left_sidebar",
          badge_text: null,
          badge_color: null,
          content_item: null,
          item_image_id: null,
          banner_image_id: null,
          set_page_link: null,
          parent_id: 57,
          created_by_id: "1",
          created_at: "2024-06-19T14:02:56.000000Z",
          product_ids: [],
          blog_ids: [],
          item_image: null,
          banner_image: null,
          child: [],
        },
        {
          id: 71,
          title: "Apple watch",
          sort: "5",
          link_type: "link",
          is_target_blank: 0,
          mega_menu: 0,
          mega_menu_type: null,
          slug: "contact-us",
          type: null,
          path: "/contact-us",
          badge_text: null,
          badge_color: null,
          content_item: null,
          item_image_id: null,
          banner_image_id: null,
          set_page_link: null,
          parent_id: 57,
          created_by_id: "1",
          created_at: "2024-06-19T14:01:13.000000Z",
          product_ids: [],
          blog_ids: [],
          item_image: null,
          banner_image: null,
          child: [],
        },
        {
          id: 70,
          title: "Power Adapter",
          sort: "6",
          link_type: "link",
          is_target_blank: 0,
          mega_menu: 0,
          mega_menu_type: null,
          slug: "compare",
          type: null,
          path: "/compare",
          badge_text: null,
          badge_color: null,
          content_item: null,
          item_image_id: null,
          banner_image_id: null,
          set_page_link: null,
          parent_id: 57,
          created_by_id: "1",
          created_at: "2024-06-19T14:00:27.000000Z",
          product_ids: [],
          blog_ids: [],
          item_image: null,
          banner_image: null,
          child: [],
        },
        {
          id: 69,
          title: "Data cable",
          sort: "7",
          link_type: "link",
          is_target_blank: 0,
          mega_menu: 0,
          mega_menu_type: null,
          slug: "checkout",
          type: null,
          path: "/checkout",
          badge_text: null,
          badge_color: null,
          content_item: null,
          item_image_id: null,
          banner_image_id: null,
          set_page_link: null,
          parent_id: 57,
          created_by_id: "1",
          created_at: "2024-06-19T13:59:57.000000Z",
          product_ids: [],
          blog_ids: [],
          item_image: null,
          banner_image: null,
          child: [],
        },
        {
          id: 73,
          title: "Mac Mini",
          sort: "8",
          link_type: "link",
          is_target_blank: 0,
          mega_menu: 0,
          mega_menu_type: null,
          slug: "search",
          type: null,
          path: "/search",
          // "badge_text": "Hot",
          badge_text: null,
          badge_color: null,
          content_item: null,
          item_image_id: null,
          banner_image_id: null,
          set_page_link: null,
          parent_id: 57,
          created_by_id: "1",
          created_at: "2024-06-19T14:03:38.000000Z",
          product_ids: [],
          blog_ids: [],
          item_image: null,
          banner_image: null,
          child: [],
        },
      ],
    },
    {
      id: 57,
      title: "Phones",
      sort: "5",
      link_type: "sub",
      is_target_blank: 0,
      mega_menu: 0,
      mega_menu_type: "simple",
      slug: "apple products",
      type: null,
      path: null,
      badge_text: null,
      badge_color: null,
      content_item: null,
      item_image_id: null,
      banner_image_id: null,
      set_page_link: null,
      parent_id: null,
      created_by_id: "1",
      created_at: "2024-06-19T13:36:23.000000Z",
      product_ids: [],
      blog_ids: [],
      item_image: null,
      banner_image: null,
      child: [
        {
          id: 65,
          title: "iPhone",
          sort: 1,
          link_type: "link",
          is_target_blank: 0,
          slug: "iphone",
          path: "/collections?layout=collection_left_sidebar",
          parent_id: 57,
          child: [],
        },
        {
          id: 66,
          title: "Samsung",
          sort: 2,
          link_type: "link",
          is_target_blank: 0,
          slug: "samsung",
          path: "/collections?layout=collection_left_sidebar",
          parent_id: 57,
          child: [],
        },
        {
          id: 67,
          title: "OnePlus",
          sort: 3,
          link_type: "link",
          is_target_blank: 0,
          slug: "oneplus",
          path: "/collections?layout=collection_left_sidebar",
          parent_id: 57,
          child: [],
        },
        {
          id: 68,
          title: "Google Pixel",
          sort: 4,
          link_type: "link",
          is_target_blank: 0,
          slug: "google-pixel",
          path: "/collections?layout=collection_left_sidebar",
          parent_id: 57,
          child: [],
        },
        {
          id: 69,
          title: "Xiaomi",
          sort: 5,
          link_type: "link",
          is_target_blank: 0,
          slug: "xiaomi",
          path: "/collections?layout=collection_left_sidebar",
          parent_id: 57,
          child: [],
        },
        {
          id: 70,
          title: "Redmi",
          sort: 6,
          link_type: "link",
          is_target_blank: 0,
          slug: "redmi",
          path: "/collections?layout=collection_left_sidebar",
          parent_id: 57,
          child: [],
        },
        {
          id: 71,
          title: "Realme",
          sort: 7,
          link_type: "link",
          is_target_blank: 0,
          slug: "realme",
          path: "/collections?layout=collection_left_sidebar",
          parent_id: 57,
          child: [],
        },
        {
          id: 72,
          title: "Vivo",
          sort: 8,
          link_type: "link",
          is_target_blank: 0,
          slug: "vivo",
          path: "/collections?layout=collection_left_sidebar",
          parent_id: 57,
          child: [],
        },
        {
          id: 73,
          title: "Oppo",
          sort: 9,
          link_type: "link",
          is_target_blank: 0,
          slug: "oppo",
          path: "/collections?layout=collection_left_sidebar",
          parent_id: 57,
          child: [],
        },
        {
          id: 74,
          title: "Infinix",
          sort: 10,
          link_type: "link",
          is_target_blank: 0,
          slug: "infinix",
          path: "/collections?layout=collection_left_sidebar",
          parent_id: 57,
          child: [],
        },
        {
          id: 75,
          title: "Tecno",
          sort: 11,
          link_type: "link",
          is_target_blank: 0,
          slug: "tecno",
          path: "/collections?layout=collection_left_sidebar",
          parent_id: 57,
          child: [],
        },
        {
          id: 76,
          title: "Nokia",
          sort: 12,
          link_type: "link",
          is_target_blank: 0,
          slug: "nokia",
          path: "/collections?layout=collection_left_sidebar",
          parent_id: 57,
          child: [],
        },
        {
          id: 77,
          title: "Motorola",
          sort: 13,
          link_type: "link",
          is_target_blank: 0,
          slug: "motorola",
          path: "/collections?layout=collection_left_sidebar",
          parent_id: 57,
          child: [],
        },
        {
          id: 78,
          title: "Huawei",
          sort: 14,
          link_type: "link",
          is_target_blank: 0,
          slug: "huawei",
          path: "/collections?layout=collection_left_sidebar",
          parent_id: 57,
          child: [],
        },
        {
          id: 79,
          title: "Honor",
          sort: 15,
          link_type: "link",
          is_target_blank: 0,
          slug: "honor",
          path: "/collections?layout=collection_left_sidebar",
          parent_id: 57,
          child: [],
        },
      ],
    },
    {
      id: 57,
      title: "Tablet",
      sort: "5",
      link_type: "sub",
      is_target_blank: 0,
      mega_menu: 0,
      mega_menu_type: "simple",
      slug: "apple products",
      type: null,
      path: null,
      badge_text: null,
      badge_color: null,
      content_item: null,
      item_image_id: null,
      banner_image_id: null,
      set_page_link: null,
      parent_id: null,
      created_by_id: "1",
      created_at: "2024-06-19T13:36:23.000000Z",
      product_ids: [],
      blog_ids: [],
      item_image: null,
      banner_image: null,
      child: [
        {
          id: 68,
          title: "Ipad",
          sort: "3",
          link_type: "link",
          is_target_blank: 0,
          mega_menu: 0,
          mega_menu_type: null,
          slug: "cart",
          type: null,
          path: "/cart",
          badge_text: null,
          badge_color: null,
          content_item: null,
          item_image_id: null,
          banner_image_id: null,
          set_page_link: null,
          parent_id: 57,
          created_by_id: "1",
          created_at: "2024-06-19T13:59:14.000000Z",
          product_ids: [],
          blog_ids: [],
          item_image: null,
          banner_image: null,
          child: [],
        },
        {
          id: 58,
          title: "Tablet",
          sort: "0",
          link_type: "sub",
          is_target_blank: 0,
          mega_menu: 0,
          mega_menu_type: "simple",
          slug: "account",
          type: null,
          path: null,
          badge_text: null,
          badge_color: null,
          content_item: null,
          item_image_id: null,
          banner_image_id: null,
          set_page_link: null,
          parent_id: 57,
          created_by_id: "1",
          created_at: "2024-06-19T13:45:11.000000Z",
          product_ids: [],
          blog_ids: [],
          item_image: null,
          banner_image: null,
          child: [
            {
              id: 59,
              title: "Galaxy Tab",
              sort: "0",
              link_type: "link",
              is_target_blank: 0,
              mega_menu: 0,
              mega_menu_type: null,
              slug: "my-dashboard",
              type: null,
              path: "/collections?layout=collection_left_sidebar",
              badge_text: null,
              badge_color: null,
              content_item: null,
              item_image_id: null,
              banner_image_id: null,
              set_page_link: null,
              parent_id: 58,
              created_by_id: "1",
              created_at: "2024-06-19T13:46:05.000000Z",
              product_ids: [],
              blog_ids: [],
              item_image: null,
              banner_image: null,
              child: [],
            },
            {
              id: 60,
              title: "Honor Tab",
              sort: "1",
              link_type: "link",
              is_target_blank: 0,
              mega_menu: 0,
              mega_menu_type: null,
              slug: "my-notifications",
              type: null,
              path: "/collections?layout=collection_left_sidebar",
              badge_text: null,
              badge_color: null,
              content_item: null,
              item_image_id: null,
              banner_image_id: null,
              set_page_link: null,
              parent_id: 58,
              created_by_id: "1",
              created_at: "2024-06-19T13:46:58.000000Z",
              product_ids: [],
              blog_ids: [],
              item_image: null,
              banner_image: null,
              child: [],
            },
            {
              id: 61,
              title: "Xiaomi Pad",
              sort: "2",
              link_type: "link",
              is_target_blank: 0,
              mega_menu: 0,
              mega_menu_type: null,
              slug: "bank-details",
              type: null,
              path: "/collections?layout=collection_left_sidebar",
              badge_text: null,
              badge_color: null,
              content_item: null,
              item_image_id: null,
              banner_image_id: null,
              set_page_link: null,
              parent_id: 58,
              created_by_id: "1",
              created_at: "2024-06-19T13:48:17.000000Z",
              product_ids: [],
              blog_ids: [],
              item_image: null,
              banner_image: null,
              child: [],
            },
            {
              id: 62,
              title: "Amazon",
              sort: "3",
              link_type: "link",
              is_target_blank: 0,
              mega_menu: 0,
              mega_menu_type: null,
              slug: "my-wallet",
              type: null,
              path: "/collections?layout=collection_left_sidebar",
              badge_text: null,
              badge_color: null,
              content_item: null,
              item_image_id: null,
              banner_image_id: null,
              set_page_link: null,
              parent_id: 58,
              created_by_id: "1",
              created_at: "2024-06-19T13:50:18.000000Z",
              product_ids: [],
              blog_ids: [],
              item_image: null,
              banner_image: null,
              child: [],
            },
          ],
        },
      ],
    },
    {
      id: 57,
      title: "Sound Equipment",
      sort: "5",
      link_type: "sub",
      is_target_blank: 0,
      mega_menu: 0,
      mega_menu_type: "simple",
      slug: "apple products",
      type: null,
      path: null,
      badge_text: null,
      badge_color: null,
      content_item: null,
      item_image_id: null,
      banner_image_id: null,
      set_page_link: null,
      parent_id: null,
      created_by_id: "1",
      created_at: "2024-06-19T13:36:23.000000Z",
      product_ids: [],
      blog_ids: [],
      item_image: null,
      banner_image: null,
      child: [
        {
          id: 66,
          title: "Airpods",
          sort: "1",
          link_type: "link",
          is_target_blank: 0,
          mega_menu: 0,
          mega_menu_type: null,
          slug: "about-us",
          type: null,
          path: "/collections?layout=collection_left_sidebar",
          badge_text: null,
          badge_color: null,
          content_item: null,
          item_image_id: null,
          banner_image_id: null,
          set_page_link: null,
          parent_id: 57,
          created_by_id: "1",
          created_at: "2024-06-19T13:58:14.000000Z",
          product_ids: [],
          blog_ids: [],
          item_image: null,
          banner_image: null,
          child: [],
        },
        {
          id: 67,
          title: "Overhead Headphone",
          sort: "2",
          link_type: "link",
          is_target_blank: 0,
          mega_menu: 0,
          mega_menu_type: null,
          slug: "browse-faqs",
          type: null,
          path: "/collections?layout=collection_left_sidebar",
          badge_text: null,
          badge_color: null,
          content_item: null,
          item_image_id: null,
          banner_image_id: null,
          set_page_link: null,
          parent_id: 57,
          created_by_id: "1",
          created_at: "2024-06-19T13:58:42.000000Z",
          product_ids: [],
          blog_ids: [],
          item_image: null,
          banner_image: null,
          child: [],
        },
        {
          id: 68,
          title: "Wieless Headphone",
          sort: "3",
          link_type: "link",
          is_target_blank: 0,
          mega_menu: 0,
          mega_menu_type: null,
          slug: "cart",
          type: null,
          path: "/collections?layout=collection_left_sidebar",
          badge_text: null,
          badge_color: null,
          content_item: null,
          item_image_id: null,
          banner_image_id: null,
          set_page_link: null,
          parent_id: 57,
          created_by_id: "1",
          created_at: "2024-06-19T13:59:14.000000Z",
          product_ids: [],
          blog_ids: [],
          item_image: null,
          banner_image: null,
          child: [],
        },
        {
          id: 72,
          title: "Wired Headphone",
          sort: "4",
          link_type: "link",
          is_target_blank: 0,
          mega_menu: 0,
          mega_menu_type: "simple",
          slug: "offers",
          type: null,
          path: "/collections?layout=collection_left_sidebar",
          badge_text: null,
          badge_color: null,
          content_item: null,
          item_image_id: null,
          banner_image_id: null,
          set_page_link: null,
          parent_id: 57,
          created_by_id: "1",
          created_at: "2024-06-19T14:02:56.000000Z",
          product_ids: [],
          blog_ids: [],
          item_image: null,
          banner_image: null,
          child: [],
        },
        {
          id: 58,
          title: "Speakers",
          sort: "0",
          link_type: "sub",
          is_target_blank: 0,
          mega_menu: 0,
          mega_menu_type: "simple",
          slug: "account",
          type: null,
          path: null,
          badge_text: null,
          badge_color: null,
          content_item: null,
          item_image_id: null,
          banner_image_id: null,
          set_page_link: null,
          parent_id: 57,
          created_by_id: "1",
          created_at: "2024-06-19T13:45:11.000000Z",
          product_ids: [],
          blog_ids: [],
          item_image: null,
          banner_image: null,
          child: [
            {
              id: 59,
              title: "Bluetooth Speaker",
              sort: "0",
              link_type: "link",
              is_target_blank: 0,
              mega_menu: 0,
              mega_menu_type: null,
              slug: "my-dashboard",
              type: null,
              path: "/collections?layout=collection_left_sidebar",
              badge_text: null,
              badge_color: null,
              content_item: null,
              item_image_id: null,
              banner_image_id: null,
              set_page_link: null,
              parent_id: 58,
              created_by_id: "1",
              created_at: "2024-06-19T13:46:05.000000Z",
              product_ids: [],
              blog_ids: [],
              item_image: null,
              banner_image: null,
              child: [],
            },
            {
              id: 60,
              title: "Smart speaker",
              sort: "1",
              link_type: "link",
              is_target_blank: 0,
              mega_menu: 0,
              mega_menu_type: null,
              slug: "my-notifications",
              type: null,
              path: "/collections?layout=collection_left_sidebar",
              badge_text: null,
              badge_color: null,
              content_item: null,
              item_image_id: null,
              banner_image_id: null,
              set_page_link: null,
              parent_id: 58,
              created_by_id: "1",
              created_at: "2024-06-19T13:46:58.000000Z",
              product_ids: [],
              blog_ids: [],
              item_image: null,
              banner_image: null,
              child: [],
            },
            {
              id: 61,
              title: "Sound Bar",
              sort: "2",
              link_type: "link",
              is_target_blank: 0,
              mega_menu: 0,
              mega_menu_type: null,
              slug: "bank-details",
              type: null,
              path: "/collections?layout=collection_left_sidebar",
              badge_text: null,
              badge_color: null,
              content_item: null,
              item_image_id: null,
              banner_image_id: null,
              set_page_link: null,
              parent_id: 58,
              created_by_id: "1",
              created_at: "2024-06-19T13:48:17.000000Z",
              product_ids: [],
              blog_ids: [],
              item_image: null,
              banner_image: null,
              child: [],
            },
            
          ],
        },
      ],
    },
    {
      id: 57,
      title: "Power & Accessories",
      sort: "5",
      link_type: "sub",
      is_target_blank: 0,
      mega_menu: 0,
      mega_menu_type: "simple",
      slug: "apple products",
      type: null,
      path: null,
      badge_text: null,
      badge_color: null,
      content_item: null,
      item_image_id: null,
      banner_image_id: null,
      set_page_link: null,
      parent_id: null,
      created_by_id: "1",
      created_at: "2024-06-19T13:36:23.000000Z",
      product_ids: [],
      blog_ids: [],
      item_image: null,
      banner_image: null,
      child: [
        {
          id: 58,
          title: "Cables",
          sort: "0",
          link_type: "sub",
          is_target_blank: 0,
          mega_menu: 0,
          mega_menu_type: "simple",
          slug: "account",
          type: null,
          path: null,
          badge_text: null,
          badge_color: null,
          content_item: null,
          item_image_id: null,
          banner_image_id: null,
          set_page_link: null,
          parent_id: 57,
          created_by_id: "1",
          created_at: "2024-06-19T13:45:11.000000Z",
          product_ids: [],
          blog_ids: [],
          item_image: null,
          banner_image: null,
          child: [
            {
              id: 59,
              title: "IPhone 17 Pro Max",
              sort: "0",
              link_type: "link",
              is_target_blank: 0,
              mega_menu: 0,
              mega_menu_type: null,
              slug: "my-dashboard",
              type: null,
              path: "/account/dashboard",
              badge_text: null,
              badge_color: null,
              content_item: null,
              item_image_id: null,
              banner_image_id: null,
              set_page_link: null,
              parent_id: 58,
              created_by_id: "1",
              created_at: "2024-06-19T13:46:05.000000Z",
              product_ids: [],
              blog_ids: [],
              item_image: null,
              banner_image: null,
              child: [],
            },
            {
              id: 60,
              title: "My Notifications",
              sort: "1",
              link_type: "link",
              is_target_blank: 0,
              mega_menu: 0,
              mega_menu_type: null,
              slug: "my-notifications",
              type: null,
              path: "/account/notifications",
              badge_text: null,
              badge_color: null,
              content_item: null,
              item_image_id: null,
              banner_image_id: null,
              set_page_link: null,
              parent_id: 58,
              created_by_id: "1",
              created_at: "2024-06-19T13:46:58.000000Z",
              product_ids: [],
              blog_ids: [],
              item_image: null,
              banner_image: null,
              child: [],
            },
            {
              id: 61,
              title: "Bank Details",
              sort: "2",
              link_type: "link",
              is_target_blank: 0,
              mega_menu: 0,
              mega_menu_type: null,
              slug: "bank-details",
              type: null,
              path: "/account/bank-details",
              badge_text: null,
              badge_color: null,
              content_item: null,
              item_image_id: null,
              banner_image_id: null,
              set_page_link: null,
              parent_id: 58,
              created_by_id: "1",
              created_at: "2024-06-19T13:48:17.000000Z",
              product_ids: [],
              blog_ids: [],
              item_image: null,
              banner_image: null,
              child: [],
            },
            {
              id: 62,
              title: "My Wallet",
              sort: "3",
              link_type: "link",
              is_target_blank: 0,
              mega_menu: 0,
              mega_menu_type: null,
              slug: "my-wallet",
              type: null,
              path: "/account/wallet",
              badge_text: null,
              badge_color: null,
              content_item: null,
              item_image_id: null,
              banner_image_id: null,
              set_page_link: null,
              parent_id: 58,
              created_by_id: "1",
              created_at: "2024-06-19T13:50:18.000000Z",
              product_ids: [],
              blog_ids: [],
              item_image: null,
              banner_image: null,
              child: [],
            },
            {
              id: 63,
              title: "My point",
              sort: "4",
              link_type: "link",
              is_target_blank: 0,
              mega_menu: 0,
              mega_menu_type: null,
              slug: "my-point",
              type: null,
              path: "account/point",
              badge_text: null,
              badge_color: null,
              content_item: null,
              item_image_id: null,
              banner_image_id: null,
              set_page_link: null,
              parent_id: 58,
              created_by_id: "1",
              created_at: "2024-06-19T13:50:53.000000Z",
              product_ids: [],
              blog_ids: [],
              item_image: null,
              banner_image: null,
              child: [],
            },
            {
              id: 64,
              title: "My Order",
              sort: "5",
              link_type: "link",
              is_target_blank: 0,
              mega_menu: 0,
              mega_menu_type: null,
              slug: "my-order",
              type: null,
              path: "/account/order",
              badge_text: null,
              badge_color: null,
              content_item: null,
              item_image_id: null,
              banner_image_id: null,
              set_page_link: null,
              parent_id: 58,
              created_by_id: "1",
              created_at: "2024-06-19T13:51:57.000000Z",
              product_ids: [],
              blog_ids: [],
              item_image: null,
              banner_image: null,
              child: [],
            },
            {
              id: 65,
              title: "Refund History",
              sort: "6",
              link_type: "link",
              is_target_blank: 0,
              mega_menu: 0,
              mega_menu_type: null,
              slug: "refund-history",
              type: null,
              path: "/account/refund",
              badge_text: null,
              badge_color: null,
              content_item: null,
              item_image_id: null,
              banner_image_id: null,
              set_page_link: null,
              parent_id: 58,
              created_by_id: "1",
              created_at: "2024-06-19T13:54:23.000000Z",
              product_ids: [],
              blog_ids: [],
              item_image: null,
              banner_image: null,
              child: [],
            },
          ],
        },
        {
          id: 66,
          title: "Power Adapter",
          sort: "1",
          link_type: "link",
          is_target_blank: 0,
          mega_menu: 0,
          mega_menu_type: null,
          slug: "about-us",
          type: null,
          path: "/about-us",
          badge_text: null,
          badge_color: null,
          content_item: null,
          item_image_id: null,
          banner_image_id: null,
          set_page_link: null,
          parent_id: 57,
          created_by_id: "1",
          created_at: "2024-06-19T13:58:14.000000Z",
          product_ids: [],
          blog_ids: [],
          item_image: null,
          banner_image: null,
          child: [],
        },
        {
          id: 67,
          title: "Power Bank",
          sort: "2",
          link_type: "link",
          is_target_blank: 0,
          mega_menu: 0,
          mega_menu_type: null,
          slug: "browse-faqs",
          type: null,
          path: "/faq",
          badge_text: null,
          badge_color: null,
          content_item: null,
          item_image_id: null,
          banner_image_id: null,
          set_page_link: null,
          parent_id: 57,
          created_by_id: "1",
          created_at: "2024-06-19T13:58:42.000000Z",
          product_ids: [],
          blog_ids: [],
          item_image: null,
          banner_image: null,
          child: [],
        },
        {
          id: 68,
          title: "Wireless Charger",
          sort: "3",
          link_type: "link",
          is_target_blank: 0,
          mega_menu: 0,
          mega_menu_type: null,
          slug: "cart",
          type: null,
          path: "/cart",
          badge_text: null,
          badge_color: null,
          content_item: null,
          item_image_id: null,
          banner_image_id: null,
          set_page_link: null,
          parent_id: 57,
          created_by_id: "1",
          created_at: "2024-06-19T13:59:14.000000Z",
          product_ids: [],
          blog_ids: [],
          item_image: null,
          banner_image: null,
          child: [],
        },
        {
          id: 68,
          title: "Power socket & Plug",
          sort: "3",
          link_type: "link",
          is_target_blank: 0,
          mega_menu: 0,
          mega_menu_type: null,
          slug: "cart",
          type: null,
          path: "/cart",
          badge_text: null,
          badge_color: null,
          content_item: null,
          item_image_id: null,
          banner_image_id: null,
          set_page_link: null,
          parent_id: 57,
          created_by_id: "1",
          created_at: "2024-06-19T13:59:14.000000Z",
          product_ids: [],
          blog_ids: [],
          item_image: null,
          banner_image: null,
          child: [],
        },
      ],
    },
    {
      id: 57,
      title: "Fitness & Wearable",
      sort: "5",
      link_type: "sub",
      is_target_blank: 0,
      mega_menu: 0,
      mega_menu_type: "simple",
      slug: "apple products",
      type: null,
      path: null,
      badge_text: null,
      badge_color: null,
      content_item: null,
      item_image_id: null,
      banner_image_id: null,
      set_page_link: null,
      parent_id: null,
      created_by_id: "1",
      created_at: "2024-06-19T13:36:23.000000Z",
      product_ids: [],
      blog_ids: [],
      item_image: null,
      banner_image: null,
      child: [
        {
          id: 66,
          title: "Power Adapter",
          sort: "1",
          link_type: "link",
          is_target_blank: 0,
          mega_menu: 0,
          mega_menu_type: null,
          slug: "about-us",
          type: null,
          path: "/about-us",
          badge_text: null,
          badge_color: null,
          content_item: null,
          item_image_id: null,
          banner_image_id: null,
          set_page_link: null,
          parent_id: 57,
          created_by_id: "1",
          created_at: "2024-06-19T13:58:14.000000Z",
          product_ids: [],
          blog_ids: [],
          item_image: null,
          banner_image: null,
          child: [],
        },
        {
          id: 67,
          title: "Power Bank",
          sort: "2",
          link_type: "link",
          is_target_blank: 0,
          mega_menu: 0,
          mega_menu_type: null,
          slug: "browse-faqs",
          type: null,
          path: "/faq",
          badge_text: null,
          badge_color: null,
          content_item: null,
          item_image_id: null,
          banner_image_id: null,
          set_page_link: null,
          parent_id: 57,
          created_by_id: "1",
          created_at: "2024-06-19T13:58:42.000000Z",
          product_ids: [],
          blog_ids: [],
          item_image: null,
          banner_image: null,
          child: [],
        },
        {
          id: 58,
          title: "Cables",
          sort: "0",
          link_type: "sub",
          is_target_blank: 0,
          mega_menu: 0,
          mega_menu_type: "simple",
          slug: "account",
          type: null,
          path: null,
          badge_text: null,
          badge_color: null,
          content_item: null,
          item_image_id: null,
          banner_image_id: null,
          set_page_link: null,
          parent_id: 57,
          created_by_id: "1",
          created_at: "2024-06-19T13:45:11.000000Z",
          product_ids: [],
          blog_ids: [],
          item_image: null,
          banner_image: null,
          child: [
            {
              id: 59,
              title: "IPhone 17 Pro Max",
              sort: "0",
              link_type: "link",
              is_target_blank: 0,
              mega_menu: 0,
              mega_menu_type: null,
              slug: "my-dashboard",
              type: null,
              path: "/account/dashboard",
              badge_text: null,
              badge_color: null,
              content_item: null,
              item_image_id: null,
              banner_image_id: null,
              set_page_link: null,
              parent_id: 58,
              created_by_id: "1",
              created_at: "2024-06-19T13:46:05.000000Z",
              product_ids: [],
              blog_ids: [],
              item_image: null,
              banner_image: null,
              child: [],
            },
            {
              id: 60,
              title: "My Notifications",
              sort: "1",
              link_type: "link",
              is_target_blank: 0,
              mega_menu: 0,
              mega_menu_type: null,
              slug: "my-notifications",
              type: null,
              path: "/account/notifications",
              badge_text: null,
              badge_color: null,
              content_item: null,
              item_image_id: null,
              banner_image_id: null,
              set_page_link: null,
              parent_id: 58,
              created_by_id: "1",
              created_at: "2024-06-19T13:46:58.000000Z",
              product_ids: [],
              blog_ids: [],
              item_image: null,
              banner_image: null,
              child: [],
            },
            {
              id: 61,
              title: "Bank Details",
              sort: "2",
              link_type: "link",
              is_target_blank: 0,
              mega_menu: 0,
              mega_menu_type: null,
              slug: "bank-details",
              type: null,
              path: "/account/bank-details",
              badge_text: null,
              badge_color: null,
              content_item: null,
              item_image_id: null,
              banner_image_id: null,
              set_page_link: null,
              parent_id: 58,
              created_by_id: "1",
              created_at: "2024-06-19T13:48:17.000000Z",
              product_ids: [],
              blog_ids: [],
              item_image: null,
              banner_image: null,
              child: [],
            },
            {
              id: 62,
              title: "My Wallet",
              sort: "3",
              link_type: "link",
              is_target_blank: 0,
              mega_menu: 0,
              mega_menu_type: null,
              slug: "my-wallet",
              type: null,
              path: "/account/wallet",
              badge_text: null,
              badge_color: null,
              content_item: null,
              item_image_id: null,
              banner_image_id: null,
              set_page_link: null,
              parent_id: 58,
              created_by_id: "1",
              created_at: "2024-06-19T13:50:18.000000Z",
              product_ids: [],
              blog_ids: [],
              item_image: null,
              banner_image: null,
              child: [],
            },
            {
              id: 63,
              title: "My point",
              sort: "4",
              link_type: "link",
              is_target_blank: 0,
              mega_menu: 0,
              mega_menu_type: null,
              slug: "my-point",
              type: null,
              path: "account/point",
              badge_text: null,
              badge_color: null,
              content_item: null,
              item_image_id: null,
              banner_image_id: null,
              set_page_link: null,
              parent_id: 58,
              created_by_id: "1",
              created_at: "2024-06-19T13:50:53.000000Z",
              product_ids: [],
              blog_ids: [],
              item_image: null,
              banner_image: null,
              child: [],
            },
            {
              id: 64,
              title: "My Order",
              sort: "5",
              link_type: "link",
              is_target_blank: 0,
              mega_menu: 0,
              mega_menu_type: null,
              slug: "my-order",
              type: null,
              path: "/account/order",
              badge_text: null,
              badge_color: null,
              content_item: null,
              item_image_id: null,
              banner_image_id: null,
              set_page_link: null,
              parent_id: 58,
              created_by_id: "1",
              created_at: "2024-06-19T13:51:57.000000Z",
              product_ids: [],
              blog_ids: [],
              item_image: null,
              banner_image: null,
              child: [],
            },
            {
              id: 65,
              title: "Refund History",
              sort: "6",
              link_type: "link",
              is_target_blank: 0,
              mega_menu: 0,
              mega_menu_type: null,
              slug: "refund-history",
              type: null,
              path: "/account/refund",
              badge_text: null,
              badge_color: null,
              content_item: null,
              item_image_id: null,
              banner_image_id: null,
              set_page_link: null,
              parent_id: 58,
              created_by_id: "1",
              created_at: "2024-06-19T13:54:23.000000Z",
              product_ids: [],
              blog_ids: [],
              item_image: null,
              banner_image: null,
              child: [],
            },
          ],
        },
        {
          id: 68,
          title: "Wireless Charger",
          sort: "3",
          link_type: "link",
          is_target_blank: 0,
          mega_menu: 0,
          mega_menu_type: null,
          slug: "cart",
          type: null,
          path: "/cart",
          badge_text: null,
          badge_color: null,
          content_item: null,
          item_image_id: null,
          banner_image_id: null,
          set_page_link: null,
          parent_id: 57,
          created_by_id: "1",
          created_at: "2024-06-19T13:59:14.000000Z",
          product_ids: [],
          blog_ids: [],
          item_image: null,
          banner_image: null,
          child: [],
        },
      ],
    },
    {
      id: 57,
      title: "Peripherals",
      sort: "5",
      link_type: "sub",
      is_target_blank: 0,
      mega_menu: 0,
      mega_menu_type: "simple",
      slug: "apple products",
      type: null,
      path: null,
      badge_text: null,
      badge_color: null,
      content_item: null,
      item_image_id: null,
      banner_image_id: null,
      set_page_link: null,
      parent_id: null,
      created_by_id: "1",
      created_at: "2024-06-19T13:36:23.000000Z",
      product_ids: [],
      blog_ids: [],
      item_image: null,
      banner_image: null,
      child: [
        {
          id: 66,
          title: "Macbook",
          sort: "1",
          link_type: "link",
          is_target_blank: 0,
          mega_menu: 0,
          mega_menu_type: null,
          slug: "about-us",
          type: null,
          path: "/about-us",
          badge_text: null,
          badge_color: null,
          content_item: null,
          item_image_id: null,
          banner_image_id: null,
          set_page_link: null,
          parent_id: 57,
          created_by_id: "1",
          created_at: "2024-06-19T13:58:14.000000Z",
          product_ids: [],
          blog_ids: [],
          item_image: null,
          banner_image: null,
          child: [],
        },
        {
          id: 67,
          title: "Browse FAQs",
          sort: "2",
          link_type: "link",
          is_target_blank: 0,
          mega_menu: 0,
          mega_menu_type: null,
          slug: "browse-faqs",
          type: null,
          path: "/faq",
          badge_text: null,
          badge_color: null,
          content_item: null,
          item_image_id: null,
          banner_image_id: null,
          set_page_link: null,
          parent_id: 57,
          created_by_id: "1",
          created_at: "2024-06-19T13:58:42.000000Z",
          product_ids: [],
          blog_ids: [],
          item_image: null,
          banner_image: null,
          child: [],
        },
        {
          id: 68,
          title: "Cart",
          sort: "3",
          link_type: "link",
          is_target_blank: 0,
          mega_menu: 0,
          mega_menu_type: null,
          slug: "cart",
          type: null,
          path: "/cart",
          badge_text: null,
          badge_color: null,
          content_item: null,
          item_image_id: null,
          banner_image_id: null,
          set_page_link: null,
          parent_id: 57,
          created_by_id: "1",
          created_at: "2024-06-19T13:59:14.000000Z",
          product_ids: [],
          blog_ids: [],
          item_image: null,
          banner_image: null,
          child: [],
        },
        {
          id: 72,
          title: "Offers",
          sort: "4",
          link_type: "link",
          is_target_blank: 0,
          mega_menu: 0,
          mega_menu_type: "simple",
          slug: "offers",
          type: null,
          path: "/offers",
          badge_text: null,
          badge_color: null,
          content_item: null,
          item_image_id: null,
          banner_image_id: null,
          set_page_link: null,
          parent_id: 57,
          created_by_id: "1",
          created_at: "2024-06-19T14:02:56.000000Z",
          product_ids: [],
          blog_ids: [],
          item_image: null,
          banner_image: null,
          child: [],
        },
        {
          id: 71,
          title: "Contact Us",
          sort: "5",
          link_type: "link",
          is_target_blank: 0,
          mega_menu: 0,
          mega_menu_type: null,
          slug: "contact-us",
          type: null,
          path: "/contact-us",
          badge_text: null,
          badge_color: null,
          content_item: null,
          item_image_id: null,
          banner_image_id: null,
          set_page_link: null,
          parent_id: 57,
          created_by_id: "1",
          created_at: "2024-06-19T14:01:13.000000Z",
          product_ids: [],
          blog_ids: [],
          item_image: null,
          banner_image: null,
          child: [],
        },
        {
          id: 70,
          title: "Compare",
          sort: "6",
          link_type: "link",
          is_target_blank: 0,
          mega_menu: 0,
          mega_menu_type: null,
          slug: "compare",
          type: null,
          path: "/compare",
          badge_text: null,
          badge_color: null,
          content_item: null,
          item_image_id: null,
          banner_image_id: null,
          set_page_link: null,
          parent_id: 57,
          created_by_id: "1",
          created_at: "2024-06-19T14:00:27.000000Z",
          product_ids: [],
          blog_ids: [],
          item_image: null,
          banner_image: null,
          child: [],
        },
        {
          id: 69,
          title: "Checkout",
          sort: "7",
          link_type: "link",
          is_target_blank: 0,
          mega_menu: 0,
          mega_menu_type: null,
          slug: "checkout",
          type: null,
          path: "/checkout",
          badge_text: null,
          badge_color: null,
          content_item: null,
          item_image_id: null,
          banner_image_id: null,
          set_page_link: null,
          parent_id: 57,
          created_by_id: "1",
          created_at: "2024-06-19T13:59:57.000000Z",
          product_ids: [],
          blog_ids: [],
          item_image: null,
          banner_image: null,
          child: [],
        },
        {
          id: 73,
          title: "Search",
          sort: "8",
          link_type: "link",
          is_target_blank: 0,
          mega_menu: 0,
          mega_menu_type: null,
          slug: "search",
          type: null,
          path: "/search",
          badge_text: "Hot",
          badge_color: null,
          content_item: null,
          item_image_id: null,
          banner_image_id: null,
          set_page_link: null,
          parent_id: 57,
          created_by_id: "1",
          created_at: "2024-06-19T14:03:38.000000Z",
          product_ids: [],
          blog_ids: [],
          item_image: null,
          banner_image: null,
          child: [],
        },
        {
          id: 74,
          title: "Wishlist",
          sort: "9",
          link_type: "link",
          is_target_blank: 0,
          mega_menu: 0,
          mega_menu_type: null,
          slug: "wishlist",
          type: null,
          path: "/wishlist",
          badge_text: null,
          badge_color: null,
          content_item: null,
          item_image_id: null,
          banner_image_id: null,
          set_page_link: null,
          parent_id: 57,
          created_by_id: "1",
          created_at: "2024-06-19T14:06:37.000000Z",
          product_ids: [],
          blog_ids: [],
          item_image: null,
          banner_image: null,
          child: [],
        },
        {
          id: 75,
          title: "404",
          sort: "10",
          link_type: "link",
          is_target_blank: 0,
          mega_menu: 0,
          mega_menu_type: null,
          slug: "404",
          type: null,
          path: "/404",
          badge_text: null,
          badge_color: null,
          content_item: null,
          item_image_id: null,
          banner_image_id: null,
          set_page_link: null,
          parent_id: 57,
          created_by_id: "1",
          created_at: "2024-06-19T14:08:06.000000Z",
          product_ids: [],
          blog_ids: [],
          item_image: null,
          banner_image: null,
          child: [],
        },
      ],
    },
    {
      id: 57,
      title: "Drone",
      sort: "5",
      link_type: "sub",
      is_target_blank: 0,
      mega_menu: 0,
      mega_menu_type: "simple",
      slug: "apple products",
      type: null,
      path: null,
      badge_text: null,
      badge_color: null,
      content_item: null,
      item_image_id: null,
      banner_image_id: null,
      set_page_link: null,
      parent_id: null,
      created_by_id: "1",
      created_at: "2024-06-19T13:36:23.000000Z",
      product_ids: [],
      blog_ids: [],
      item_image: null,
      banner_image: null,
      child: [
        {
          id: 66,
          title: "Macbook",
          sort: "1",
          link_type: "link",
          is_target_blank: 0,
          mega_menu: 0,
          mega_menu_type: null,
          slug: "about-us",
          type: null,
          path: "/about-us",
          badge_text: null,
          badge_color: null,
          content_item: null,
          item_image_id: null,
          banner_image_id: null,
          set_page_link: null,
          parent_id: 57,
          created_by_id: "1",
          created_at: "2024-06-19T13:58:14.000000Z",
          product_ids: [],
          blog_ids: [],
          item_image: null,
          banner_image: null,
          child: [],
        },
        {
          id: 67,
          title: "Browse FAQs",
          sort: "2",
          link_type: "link",
          is_target_blank: 0,
          mega_menu: 0,
          mega_menu_type: null,
          slug: "browse-faqs",
          type: null,
          path: "/faq",
          badge_text: null,
          badge_color: null,
          content_item: null,
          item_image_id: null,
          banner_image_id: null,
          set_page_link: null,
          parent_id: 57,
          created_by_id: "1",
          created_at: "2024-06-19T13:58:42.000000Z",
          product_ids: [],
          blog_ids: [],
          item_image: null,
          banner_image: null,
          child: [],
        },
        {
          id: 68,
          title: "Cart",
          sort: "3",
          link_type: "link",
          is_target_blank: 0,
          mega_menu: 0,
          mega_menu_type: null,
          slug: "cart",
          type: null,
          path: "/cart",
          badge_text: null,
          badge_color: null,
          content_item: null,
          item_image_id: null,
          banner_image_id: null,
          set_page_link: null,
          parent_id: 57,
          created_by_id: "1",
          created_at: "2024-06-19T13:59:14.000000Z",
          product_ids: [],
          blog_ids: [],
          item_image: null,
          banner_image: null,
          child: [],
        },
        {
          id: 72,
          title: "Offers",
          sort: "4",
          link_type: "link",
          is_target_blank: 0,
          mega_menu: 0,
          mega_menu_type: "simple",
          slug: "offers",
          type: null,
          path: "/offers",
          badge_text: null,
          badge_color: null,
          content_item: null,
          item_image_id: null,
          banner_image_id: null,
          set_page_link: null,
          parent_id: 57,
          created_by_id: "1",
          created_at: "2024-06-19T14:02:56.000000Z",
          product_ids: [],
          blog_ids: [],
          item_image: null,
          banner_image: null,
          child: [],
        },
      ],
    },
  ];
  useEffect(() => {
    isLoading && refetch();
  }, [isLoading]);

  return (
    <>
      {isLoading ? (
        <ul className="skeleton-menu navbar-nav">
          <li></li>
          <li></li>
          <li></li>
          <li></li>
          <li></li>
          <li></li>
          <li></li>
        </ul>
      ) : (
        <ul className="navbar-nav">
          {headerMenu?.map((menu, i) => (
            <MenuList
              menu={menu}
              key={i}
              customClass={`${!menu?.path ? "dropdown" : ""} nav-item `}
              level={0}
              isOpen={isOpen}
              setIsOpen={setIsOpen}
            />
          ))}
        </ul>
      )}
    </>
  );
};

export default MainHeaderMenu;
